### PR TITLE
added a face mask detection code

### PR DESCRIPTION
**Pull request by mrsparkle-70**
See to it

## What type of PR is this? (check all applicable)

- [x] 🚀 Added Name : Face mask detection
- [x] ✨ Feature: Detects face vs Mask
- [x] 🌟 stared the repo
- [x] 🐛 Grammatical Error
- [ ] 📝 Documentation Update
- [x] 🚩 Other

## Add Link of GitHub Prof
https://github.com/mrsparkle-70

### CODE REVIEW

**Comment by mrsparkle-70** [comment]
@Nitin-Diwakar see to it and please give reviews

**Comment by Nitin-Diwakar** [comment]
- Also update the contributing.md file

**Comment by mrsparkle-70** [comment]
Can u check now and let me know ?
Thanks & Regards
Subham Sinha

**Review by Nitin-Diwakar — APPROVED** [review]
You are good to go.

**Review by Nitin-Diwakar — APPROVED** [review]
Processing the merging

**Comment by mrsparkle-70** [comment]
So will it get merged ? @Nitin-Diwakar

**Comment by mrsparkle-70** [comment]
> Processing the merging

Thanks 
Eagerly waiting for it @Nitin-Diwakar

**Comment by Nitin-Diwakar** [comment]
your pull request is accepted, for last please add your name in the **` CONTRIBUTING.md`**

**Pull request merged**
