### PR TITLE
Full Body Monitoring using Mediapipe

### PR DESCRIPTION
**Pull request by mrsparkle-70**
## What type of PR is this? (check all applicable)

- [x] 🚀 Added Name
- [x] ✨ Feature
- [ ] 🌟 stared the repo
- [ ] 🐛 Grammatical Error
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Add Link of GitHub Prof
My github profile: https://github.com/mrsparkle-70

### CODE REVIEW

**Comment by mrsparkle-70** [comment]
@Nitin-Diwakar Can u check it

**Comment by Nitin-Diwakar** [comment]
I only accept 1 personal project. This repository is for a person creating a project/analysis report by given dataset in the `for data analysis` directory. If you want to pull request, read about the rules of this repository in the `Readme.md` section.

**Comment by mrsparkle-70** [comment]
Ok sir

**Comment by mrsparkle-70** [comment]
Sir
Should I upload Datasets then ?
I am not clear about this
It would be very nice if u clear this doubt of mine

**Comment by Nitin-Diwakar** [comment]
In the `For data analysis` directory there are different types of datasets, pick one of them and push your analysis report to the repo. You can use any application for analysis such as PowerBI, jupyter notebook, excel, etc

**Pull request closed without merging**
